"use strict";
let anyEstaDevuelta;
anyEstaDevuelta = 3;
anyEstaDevuelta = true;
anyEstaDevuelta = 'string';
let stringTest = 'verificar';
stringTest = anyEstaDevuelta;
let unknowValue;
unknowValue = 3;
unknowValue = 'opa';
unknowValue = false;
unknowValue = 'no es';
let stringTest2 = 'ahora es';
stringTest2 = unknowValue;
